name: simpeg-emg3d
channels:
    - conda-forge
dependencies:
    - python
    - simpeg>=0.22.1
    - jupyter
    - ipykernel
    - xarray
    - matplotlib
    - ipympl
    - h5py
    - tqdm
    - scooby
    - pip
    - pip:
      - git+https://github.com/emsig/emg3d@inv-simpeg
